// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBCAhWN0nBQpECNN5TBIWHsm9BgaKHGf0',
    appId: '1:787297789634:web:1b11d9e8f901284cba3d5b',
    messagingSenderId: '787297789634',
    projectId: 'denemeapp-6b435',
    authDomain: 'denemeapp-6b435.firebaseapp.com',
    databaseURL: 'https://denemeapp-6b435-default-rtdb.firebaseio.com',
    storageBucket: 'denemeapp-6b435.appspot.com',
    measurementId: 'G-QGJMBYEGHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn-Hf55aE75XBwJgYo8hL_Jgm2Cq7pS0Y',
    appId: '1:787297789634:android:25d58d746edb5df3ba3d5b',
    messagingSenderId: '787297789634',
    projectId: 'denemeapp-6b435',
    databaseURL: 'https://denemeapp-6b435-default-rtdb.firebaseio.com',
    storageBucket: 'denemeapp-6b435.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKOr0LHHQm9mf5RDbSbqqUDFXZWOSk00',
    appId: '1:787297789634:ios:da2923ce7507e547ba3d5b',
    messagingSenderId: '787297789634',
    projectId: 'denemeapp-6b435',
    databaseURL: 'https://denemeapp-6b435-default-rtdb.firebaseio.com',
    storageBucket: 'denemeapp-6b435.appspot.com',
    iosBundleId: 'com.example.hadiBulsana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgKOr0LHHQm9mf5RDbSbqqUDFXZWOSk00',
    appId: '1:787297789634:ios:0a7aa32cce55396cba3d5b',
    messagingSenderId: '787297789634',
    projectId: 'denemeapp-6b435',
    databaseURL: 'https://denemeapp-6b435-default-rtdb.firebaseio.com',
    storageBucket: 'denemeapp-6b435.appspot.com',
    iosBundleId: 'com.example.hadiBulsana.RunnerTests',
  );
}
